version: '3.4'

services:
  mssql_dev:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: "mssql_dev"
    user: root
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: MyPassword@1
    volumes:
      - ./data/mssql/data/:/var/opt/mssql/data
      - ./data/mssql/log/:/var/opt/mssql/log
      - ./data/mssql/secrets/:/var/opt/mssql/secrets
    ports:
      - 1433:1433
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    hostname: my-rabbit
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
  sevenpeaks.vts.web:
    image: ${DOCKER_REGISTRY-}sevenpeaksvts
    build:
      context: .
      dockerfile: SevenPeaks.VTS.Web/Dockerfile

